### ISSUE TITLE
crashes upon opening settings 

### ISSUE THREAD

**Issue by duolaameng903** [Alberto97/OUILookup#343]
The app immediately closes after the settings button is tapped

https://github.com/Alberto97/OUILookup/assets/144056715/dba31137-ae87-4810-9505-9d3f239c1497

**Comment by Alberto97** [comment]
It seems actually fixed now. Weirdly enough I did not have to do anything except update some dependencies

**Comment by duolaameng903** [comment]
Yes, it is fixed now, thank you
