### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [Alberto97/OUILookup#40]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 07 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on OUI Lookup and Database (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve OUI Lookup and Database's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by Alberto97** [comment]
Sorry for the delay, I've missed this.
I'm closing the issue because the app doesn't really use cryptography directly and doesn't handle any kind of sensitive information anyway.
Because of that even if some library I'm using does not implement encryption properly that's not an issue.
